apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: update-agent
spec:
  template:
    metadata:
      labels:
        app: update-agent
    spec:
      containers:
      - name: update-agent
        image: quay.io/coreos/container-linux-update-operator:dev
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/run/dbus
            name: var-run-dbus
          - mountPath: /etc/coreos
            name: etc-coreos
          - mountPath: /usr/share/coreos
            name: usr-share-coreos
          - mountPath: /etc/os-release
            name: etc-os-release
        env:
        # read by update-agent as the node name to manage reboots for
        - name: UPDATE_AGENT_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: etc-coreos
        hostPath:
          path: /etc/coreos
      - name: usr-share-coreos
        hostPath:
          path: /usr/share/coreos
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: update-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: update-operator
    spec:
      containers:
      - name: update-operator
        image: quay.io/coreos/container-linux-update-operator:dev
        imagePullPolicy: Always
        command:
        - "/bin/update-operator"

